FROM node:16.16.0
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
ARG DB
ARG CONNECTIONSTRING
ENV DB=${DB}
ENV CONNECTIONSTRING=${CONNECTIONSTRING}
ENV PORT=3000
ENV JWTSECRET=koG9z!rDmSELJ7#bte
EXPOSE 3000

CMD ["npm", "start"]